# Generated by Django 6.0.5 on 2026-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='product_name',
            field=models.CharField(blank=True, default='', help_text='Optional product name', max_length=100),
        ),
    ]
