# Generated by Django 6.0.5 on 2026-07-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_package_product_name'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store where this package is located', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='store.store'),
        ),
    ]
