# Generated by Django 6.0.5 on 2026-07-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_package_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('barcode_value', models.CharField(help_text='Barcode scanned at time of sale', max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg at time of sale', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price at time of sale', max_digits=10)),
                ('customer_name', models.CharField(blank=True, default='', help_text='Optional customer name', max_length=100)),
                ('customer_phone', models.CharField(blank=True, default='', help_text='Optional customer phone', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Money'), ('card', 'Card')], default='cash', max_length=20)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
