# Generated by Django 6.0.5 on 2026-07-23 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_package_product_name'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sale amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='barcode_value',
            field=models.CharField(blank=True, default='', help_text='Barcode (legacy single-item)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.package'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price (legacy)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (legacy)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_value', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.package')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.sale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
