# Generated by Django 6.0.5 on 2026-07-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_sale_total_amount_alter_sale_barcode_value_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store where this sale was made', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store.store'),
        ),
    ]
