# Generated by Django 6.0.5 on 2026-07-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store assignment (not required for managers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='store.store'),
        ),
    ]
